### ISSUE TITLE
beacon node doesn't have a parent in db with root --ropsten

### ISSUE THREAD

**Issue by basvlanat** [prysmaticlabs/prysm#10877]
# 💎 Issue
### Background
I used documentation [page](https://docs.prylabs.network/docs/next/install/install-with-docker/#downloading-the-prysm-docker-images) for run beacon node **v2.1.3-rc.3** in docker . 
### Description
I'm trying sync beacon node, for my geth node in the test network` --ropsten`. I only need it so that my geth node gets into the correct chain of blocks after [merge](https://blog.ethereum.org/2022/06/03/ropsten-merge-ttd/).
I'm running beacon node from docker, my docker-compose file:
```
version: '3.9'
services:
  beacon-test-node:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:v2.1.3-rc.3
    hostname: beacon-test-node
    volumes:
      - "/mnt/data0/beacon-test-node/data1:/data"
      - "/mnt/data0/beacon-test-node/genesis1/genesis.ssz:/genesis/genesis.ssz"
    command:
      - --datadir=/data
      - --rpc-host=0.0.0.0
      - --monitoring-host=0.0.0.0
      - --http-web3provider=http://172.16.17.6:8550
      - --genesis-state=/genesis/genesis.ssz
      - --terminal-total-difficulty-override=50000000000000000
      - --ropsten
      - --accept-terms-of-use
    ports:
      - 4000:4000
      - 13000:13000 
      - 12000:12000/udp
```
But I get an error while syncing:

 ```
time="2022-06-14 12:11:04" level=info msg="Processing block batch of size 61 starting from  0x8f1a6d3e... 65536/106255 - estimated time remaining 9m46s" blocksPerSecond=69.5 peers=5 prefix=initial-sync
 time="2022-06-14 12:11:04" level=warning msg="Batch is not processed" error="beacon node doesn't have a parent in db with root: 0x56531606c0bd5a8055c0592c2e6f822bb11e3453c3ab7f44a0e932e76b076117 (in processBatchedBlocks, slot=65536)" prefix=initial-sync
time="2022-06-14 12:11:06" level=info msg="Processing block batch of size 63 starting from  0x5f121470... 65088/106255 - estimated time remaining 9m52s" blocksPerSecond=69.5 peers=5 prefix=initial-sync
time="2022-06-14 12:11:09" level=warning msg="Batch is not processed" error="could not process block in batch: method not found: received an undefined ee error" prefix=initial-sync
time="2022-06-14 12:11:09" level=info msg="Processing block batch of size 50 starting from  0x7bc82575... 65152/106255 - estimated time remaining 13m11s" blocksPerSecond=52.0 peers=4 prefix=initial-sync
 time="2022-06-14 12:11:09" level=warning msg="Batch is not processed" error="beacon node doesn't have a parent in db with root: 0x7d3303ad6cf3dfbf55394fd50789a1616af25187984d3d56fd4fafc2f02694da (in processBatchedBlocks, slot=65152)" prefix=initial-sync
time="2022-06-14 12:11:09" level=info msg="Processing block batch of size 49 starting from  0x4d81edfc... 65218/106255 - estimated time remaining 12m34s" blocksPerSecond=54.4 peers=4 prefix=initial-sync
time="2022-06-14 12:11:09" level=warning msg="Batch is not processed" error="beacon node doesn't have a parent in db with root: 0x8d4e14afa8f31605b80c317c64852b9d2c25f1770bd80e20c659f2eb977f7b9b (in processBatchedBlocks, slot=65218)" prefix=initial-sync
 time="2022-06-14 12:11:09" level=info msg="Processing block batch of size 57 starting from  0x67aba47f... 65280/106255 - estimated time remaining 11m55s" blocksPerSecond=57.2 peers=4 prefix=initial-sync
 time="2022-06-14 12:11:09" level=warning msg="Batch is not processed" error="beacon node doesn't have a parent in db with root: 0xd99d8bd1860c47a1995458e09fa422ef7c42fed66575da26c17963e3d99af2e3 (in processBatchedBlocks, slot=65280)" prefix=initial-sync
time="2022-06-14 12:11:09" level=info msg="Processing block batch of size 58 starting from  0x6bfc01f7... 65344/106255 - estimated time remaining 11m20s" blocksPerSecond=60.1 peers=4 prefix=initial-sync
time="2022-06-14 12:11:09" level=warning msg="Batch is not processed" error="beacon node doesn't have a parent in db with root: 0x83ac86c72af236e3ce1a02d9261132d4e9a84faf64e3806178e15afc35d91221 (in processBatchedBlocks, slot=65344)" prefix=initial-sync
time="2022-06-14 12:11:09" level=info msg="Processing block batch of size 62 starting from  0x6bc69414... 65408/106255 - estimated time remaining 10m45s" blocksPerSecond=63.2 peers=4 prefix=initial-sync
 time="2022-06-14 12:11:09" level=warning msg="Batch is not processed" error="beacon node doesn't have a parent in db with root: 0xc374da4e750236af42eb4976412bfc1f96cbed3f07eac1938c42233c97c8442d (in processBatchedBlocks, slot=65408)" prefix=initial-sync
time="2022-06-14 12:11:09" level=info msg="Processing block batch of size 63 starting from  0x19d6d017... 65472/106255 - estimated time remaining 10m14s" blocksPerSecond=66.4 peers=4 prefix=initial-sync
 time="2022-06-14 12:11:09" level=warning msg="Batch is not processed" error="beacon node doesn't have a parent in db with root: 0xedacd662531617166bc7f0480812010c258d411b8bba2d359310276ec9b7adc7 (in processBatchedBlocks, slot=65472)" prefix=initial-sync
time="2022-06-14 12:11:09" level=info msg="Processing block batch of size 61 starting from  0x8f1a6d3e... 65536/106255 - estimated time remaining 9m46s" blocksPerSecond=69.5 peers=4 prefix=initial-sync
 time="2022-06-14 12:11:09" level=warning msg="Batch is not processed" error="beacon node doesn't have a parent in db with root: 0x56531606c0bd5a8055c0592c2e6f822bb11e3453c3ab7f44a0e932e76b076117 (in processBatchedBlocks, slot=65536)" prefix=initial-sync
 time="2022-06-14 12:11:10" level=info msg="Connected to new endpoint: http://172.16.17.6:8550" prefix=powchain

```
Please tell me what I'm doing wrong??

**Comment by barwod** [comment]
Hi, I have the same problem with beacon-node.

`time="2022-08-05 06:35:14" level=info msg="Processing block batch of size 33 starting from  0xc16f5d16... 115265/328976 - estimated time remaining 34m38s" blocksPerSecond=102.8 peers=35 prefix=initial-sync
time="2022-08-05 06:35:14" level=warning msg="Batch is not processed" error="beacon node doesn't have a parent in db with root: 0x0e4402bcd926011704f64f7d1c0dbbfdd4769ab5f2c0e332935ccfbb2c89e466 (in processBatchedBlocks, slot=115265)" prefix=initial-sync
time="2022-08-05 06:35:14" level=info msg="Processing block batch of size 48 starting from  0x796fd234... 115326/328976 - estimated time remaining 33m50s" blocksPerSecond=105.2 peers=35 prefix=initial-sync
time="2022-08-05 06:35:14" level=warning msg="Batch is not processed" error="beacon node doesn't have a parent in db with root: 0x554dce2be4beb977dfef5758b105928ac25e574c79abdba3cf36d3189a995954 (in processBatchedBlocks, slot=115326)" prefix=initial-sync
time="2022-08-05 06:35:14" level=info msg="Processing block batch of size 44 starting from  0xa4c0fa64... 115391/328976 - estimated time remaining 33m8s" blocksPerSecond=107.4 peers=35 prefix=initial-sync
time="2022-08-05 06:35:14" level=warning msg="Batch is not processed" error="beacon node doesn't have a parent in db with root: 0xbba3ea00bcaac3381821bfced266f765ed7b7bfdd3c739217608d0eeb33f10c1 (in processBatchedBlocks, slot=115391)" prefix=initial-sync
time="2022-08-05 06:35:14" level=info msg="Processing block batch of size 54 starting from  0xdf1028ce... 115454/328976 - estimated time remaining 32m19s" blocksPerSecond=110.1 peers=35 prefix=initial-sync
time="2022-08-05 06:35:14" level=warning msg="Batch is not processed" error="beacon node doesn't have a parent in db with root: 0x3a13e46202ad29397ad05a692d1a729ef9e4be80001db2c72e649356eab65b00 (in processBatchedBlocks, slot=115454)" prefix=initial-sync
time="2022-08-05 06:35:14" level=info msg="Processing block batch of size 45 starting from  0x8758e34a... 115518/328976 - estimated time remaining 31m39s" blocksPerSecond=112.3 peers=35 prefix=initial-sync
time="2022-08-05 06:35:14" level=warning msg="Batch is not processed" error="beacon node doesn't have a parent in db with root: 0x5356e58c5fe6f7a6c6c37af34e46b284699fb7b448759779901615b235ff3222 (in processBatchedBlocks, slot=115518)" prefix=initial-sync
time="2022-08-05 06:35:17" level=info msg="Processing block batch of size 60 starting from  0xa7e7f76b... 115136/328976 - estimated time remaining 35m53s" blocksPerSecond=99.3 peers=35 prefix=initial-sync
time="2022-08-05 06:35:17" level=warning msg="Batch is not processed" error="could not process block in batch: method not found: received an undefined ee error" prefix=initial-sync`

**Comment by artjoma** [comment]
Sepolia, v2.1.4-rc-1 and 2.1.3. Stack with initial sync.
```
time="2022-08-09 09:09:40" level=warning msg="Batch is not processed" error="could not process block in batch: could not set node to invalid: invalid nil or unknown node" prefix=initial-sync
time="2022-08-09 09:09:40" level=info msg="Processing block batch of size 60 starting from  0x8f0330c8... 352320/358548 - estimated time remaining 46s" blocksPerSecond=135.3 peers=27 prefix=initial-sync
time="2022-08-09 09:09:40" level=warning msg="Batch is not processed" error="beacon node doesn't have a parent in db with root: 0x5a72fb080d592e7bcb64ce1faf873e4333dbfe74a9b31c581e8c01ea586bf3b9 (in processBatchedBlocks, slot=352320)" prefix=initial-sync
time="2022-08-09 09:09:40" level=info msg="Processing block batch of size 58 starting from  0xfb0d78ec... 352384/358548 - estimated time remaining 44s" blocksPerSecond=138.2 peers=27 prefix=initial-sync
time="2022-08-09 09:09:40" level=warning msg="Batch is not processed" error="beacon node doesn't have a parent in db with root: 0x4ce21985d92074afcb718a4ec7519a947e4a4582a0772df458283edec71dbdcd (in processBatchedBlocks, slot=352384)" prefix=initial-sync
time="2022-08-09 09:09:40" level=info msg="Processing block batch of size 54 starting from  0xe4c041ca... 352448/358548 - estimated time remaining 43s" blocksPerSecond=140.9 peers=27 prefix=initial-sync
time="2022-08-09 09:09:40" level=warning msg="Batch is not processed" error="beacon node doesn't have a parent in db with root: 0x1f51847958ca20e0a56fe8a3edd504dcf33593cabb24ba7e9cf807b5098a4abf (in processBatchedBlocks, slot=352448)" prefix=initial-sync
time="2022-08-09 09:09:40" level=info msg="Processing block batch of size 58 starting from  0xccad1006... 352512/358548 - estimated time remaining 41s" blocksPerSecond=143.8 peers=27 prefix=initial-sync
time="2022-08-09 09:09:40" level=warning msg="Batch is not processed" error="beacon node doesn't have a parent in db with root: 0xb1ba83ab6e1bae549a73e18d4a03c4f64dc7ea16039ec202c306601f59883478 (in processBatchedBlocks, slot=352512)" prefix=initial-sync
time="2022-08-09 09:09:40" level=info msg="Processing block batch of size 52 starting from  0xd6af50bd... 352577/358548 - estimated time remaining 40s" blocksPerSecond=146.4 peers=27 prefix=initial-sync
time="2022-08-09 09:09:40" level=warning msg="Batch is not processed" error="beacon node doesn't have a parent in db with root: 0x28a22480afeb78e39794cbb046395d5990f4c82b122f805f480fc2933aef0977 (in processBatchedBlocks, slot=352577)" prefix=initial-sync
time="2022-08-09 09:09:40" level=info msg="Processing block batch of size 52 starting from  0x8938a4ca... 352640/358548 - estimated time remaining 39s" blocksPerSecond=149.0 peers=27 prefix=initial-sync
time="2022-08-09 09:09:40" level=warning msg="Batch is not processed" error="beacon node doesn't have a parent in db with root: 0x1d9c59a9be9dbc330bbb90a88f21ba82a8925d545ba5b0bc69f07aff73dcfe8f (in processBatchedBlocks, slot=352640)" prefix=initial-sync
time="2022-08-09 09:09:40" level=info msg="Processing block batch of size 57 starting from  0xa8a97d5c... 352705/358548 - estimated time remaining 38s" blocksPerSecond=151.8 peers=27 prefix=initial-sync
time="2022-08-09 09:09:40" level=warning msg="Batch is not processed" error="beacon node doesn't have a parent in db with root: 0xa7dbece9eae38dc01f024b1080a527c612ab663cc631cf914c9c385b7e0b1c1b (in processBatchedBlocks, slot=352705)" prefix=initial-sync
````

**Comment by nisdas** [comment]
@potuz @terencechain 
```
time="2022-08-09 09:09:40" level=warning msg="Batch is not processed" error="could not process block in batch: could not set node to invalid: invalid nil or unknown node" prefix=initial-sync
```

Is this a new issue, or something resolved in develop ?

**Comment by nisdas** [comment]
@barwod You need to use the engine port in geth and connect prysm to that (8551 instead of 8545)

**Comment by nisdas** [comment]
@artjoma Can you link your ee(erigon)  logs in this time period too ? It seems related

**Comment by artjoma** [comment]
@nisdas 
Right now I updated Erigon to 2022.08.01(last stable version). Problem not solved.
Logs from Erigon
```
[INFO] [08-09|09:24:05.314] Starting Erigon on Sepolia testnet...
[INFO] [08-09|09:24:05.315] Maximum peer count                       ETH=100 total=100
[INFO] [08-09|09:24:05.315] starting HTTP APIs                       APIs=eth,net,erigon,engine,debug,trace
[INFO] [08-09|09:24:05.315] torrent verbosity                        level=WRN
[INFO] [08-09|09:24:07.424] Set global gas cap                       cap=50000000
[INFO] [08-09|09:24:07.424] Opening Database                         label=chaindata path=/mnt/md2/erigon-sepolia/erigon/chaindata/chaindata
[INFO] [08-09|09:24:07.426] Initialised chain configuration          config="{ChainID: 11155111, Homestead: 0, DAO: <nil>, DAO Support: true, Tangerine Whistle: 0, Spurious Dragon: 0, Byzantium: 0, Constantinople: 0, Petersburg: 0, Istanbul: 0, Muir Glacier: 0, Berlin: 0, London: 0, Arrow Glacier: <nil>, Gray Glacier: <nil>, Terminal Total Difficulty: 17000000000000000, Merge Netsplit: 1735371, Engine: ethash}" genesis=0x25a5cc106eea7138acab33231d7160d69cb777ee0c2c553fcddf5138993e6d>
[INFO] [08-09|09:24:07.426] Effective                                prune_flags= snapshot_flags=
[INFO] [08-09|09:24:07.427] Using snapshots                          on=false
[INFO] [08-09|09:24:07.427] Initialising Ethereum protocol           network=11155111
[INFO] [08-09|09:24:07.427] Disk storage enabled for ethash DAGs     dir=/mnt/md2/erigon-sepolia/erigon/chaindata/ethash-dags count=2
[INFO] [08-09|09:24:07.861] Starting private RPC server              on=0.0.0.0:9093
[INFO] [08-09|09:24:07.861] new subscription to logs established
[INFO] [08-09|09:24:07.861] rpc filters: subscribing to Erigon events
[INFO] [08-09|09:24:07.861] new subscription to newHeaders established
[INFO] [08-09|09:24:07.861] New txs subscriber joined
[INFO] [08-09|09:24:07.862] Reading JWT secret                       path=/mnt/md2/erigon-sepolia/erigon/chaindata/jwt.hex
[INFO] [08-09|09:24:07.862] HTTP endpoint opened for Engine API      url=localhost:8553 ws=true ws.compression=true
[INFO] [08-09|09:24:07.863] HTTP endpoint opened                     url=0.0.0.0:11020 ws=true ws.compression=true grpc=false
[INFO] [08-09|09:24:07.866] Started P2P networking                   version=66 self=enode://3cf254848fa9fb6223d7d89ff971d3663df92cf9159cb7a8be07a42a641d28e2a3efd63cba47ec964600cfafbb9329a316c655af5f90c449100daecd2be17b29@127.0.0.1:30310 name=erigon/v2022.08.1-alpha-7326fbe8/linux-amd64/go1.19
[INFO] [08-09|09:24:07.873] RPC Daemon notified of new headers       from=1658818 to=1658819 header sending=16.19µs log sending=290ns
[INFO] [08-09|09:24:07.873] [1/16 Headers] Waiting for Beacon Chain...
[INFO] [08-09|09:24:07.885] [txpool] Started
[INFO] [08-09|09:24:09.416] UnwindTo                                 block=1658816 bad_block_hash=0x0000000000000000000000000000000000000000000000000000000000000000
[INFO] [08-09|09:24:09.417] [6/7 HashState] Unwinding started        from=1658818 to=1658816 storage=false codes=true
[INFO] [08-09|09:24:09.417] [6/7 HashState] Unwinding started        from=1658818 to=1658816 storage=false codes=false
[INFO] [08-09|09:24:09.419] [6/7 HashState] Unwinding started        from=1658818 to=1658816 storage=true codes=false
[INFO] [08-09|09:24:09.422] [7/7 IntermediateHashes] Unwinding       from=1658818 to=1658816 csbucket=AccountChangeSet
[INFO] [08-09|09:24:09.423] [7/7 IntermediateHashes] Unwinding       from=1658818 to=1658816 csbucket=StorageChangeSet
[INFO] [08-09|09:24:09.430] [7/7 IntermediateHashes] Trie root       hash=0x8f37618e607845f14d47538736aecfbac2ef2d2e275003d4232747efc34f57e1
[INFO] [08-09|09:24:09.431] [5/7 Execution] Unwind Execution         from=1658818 to=1658816
[WARN] [08-09|09:24:09.437] [5/7 Execution] Execution failed         block=1658817 hash=0x6ec18e10b257326452b249705b66350c3ef2963da75da9e769c065ca0401938a err="could not apply tx 0 from block 1658817 [0xa7261682ce6b1f5d70bdacb4ee13dbf466f72e9149cfc1a756031654c180f268]: nonce too low: address 0x2f14582947E292a2eCd20C430B46f2d27CFE213c, tx: 0 state: 7"
[WARN] [08-09|09:24:09.437] Could not validate block                 err="[5/7 Execution] could not apply tx 0 from block 1658817 [0xa7261682ce6b1f5d70bdacb4ee13dbf466f72e9149cfc1a756031654c180f268]: nonce too low: address 0x2f14582947E292a2eCd20C430B46f2d27CFE213c, tx: 0 state: 7"
[WARN] [08-09|09:24:09.437] Validation failed for header             hash=0x6ec18e10b257326452b249705b66350c3ef2963da75da9e769c065ca0401938a height=1658817 err="[5/7 Execution] could not apply tx 0 from block 1658817 [0xa7261682ce6b1f5d70bdacb4ee13dbf466f72e9149cfc1a756031654c180f268]: nonce too low: address 0x2f14582947E292a2eCd20C430B46f2d27CFE213c, tx: 0 state: 7"
[INFO] [08-09|09:24:09.437] Timings (slower than 50ms)               Headers=1.563s
[INFO] [08-09|09:24:09.437] Tables                                   PlainState=28.9MB AccountChangeSet=146.8MB StorageChangeSet=66.5MB BlockTransaction=641.8MB TransactionLog=175.8MB FreeList=36.0KB ReclaimableSpace=36.0MB
[INFO] [08-09|09:24:09.437] Commit cycle                             in=11.451µs
[INFO] [08-09|09:24:09.437] RPC Daemon notified of new headers       from=1658818 to=1658819 header sending=8.851µs log sending=530ns
[INFO] [08-09|09:24:09.437] [1/16 Headers] Waiting for Beacon Chain...
[WARN] [08-09|09:24:12.270] [NewPayload] Previously known bad block  hash=0x6ec18e10b257326452b249705b66350c3ef2963da75da9e769c065ca0401938a
[WARN] [08-09|09:24:15.637] [NewPayload] Previously known bad block  hash=0x6ec18e10b257326452b249705b66350c3ef2963da75da9e769c065ca0401938a
[WARN] [08-09|09:24:18.482] [NewPayload] Previously known bad block  hash=0x6ec18e10b257326452b249705b66350c3ef2963da75da9e769c065ca0401938a
[WARN] [08-09|09:24:21.679] [NewPayload] Previously known bad block  hash=0x6ec18e10b257326452b249705b66350c3ef2963da75da9e769c065ca0401938a
[WARN] [08-09|09:24:24.255] [NewPayload] Previously known bad block  hash=0x6ec18e10b257326452b249705b66350c3ef2963da75da9e769c065ca0401938a
[WARN] [08-09|09:24:28.092] [NewPayload] Previously known bad block  hash=0x6ec18e10b257326452b249705b66350c3ef2963da75da9e769c065ca0401938a
[WARN] [08-09|09:24:30.624] [NewPayload] Previously known bad block  hash=0x6ec18e10b257326452b249705b66350c3ef2963da75da9e769c065ca0401938a
[WARN] [08-09|09:24:33.085] [NewPayload] Previously known bad block  hash=0x6ec18e10b257326452b249705b66350c3ef2963da75da9e769c065ca0401938a
[WARN] [08-09|09:24:36.467] [NewPayload] Previously known bad block  hash=0x6ec18e10b257326452b249705b66350c3ef2963da75da9e769c065ca0401938a
[WARN] [08-09|09:24:41.650] [NewPayload] Previously known bad block  hash=0x6ec18e10b257326452b249705b66350c3ef2963da75da9e769c065ca0401938a
[WARN] [08-09|09:24:44.274] [NewPayload] Previously known bad block  hash=0x6ec18e10b257326452b249705b66350c3ef2963da75da9e769c065ca0401938a
[WARN] [08-09|09:24:50.256] [NewPayload] Previously known bad block  hash=0x6ec18e10b257326452b249705b66350c3ef2963da75da9e769c065ca0401938a
[WARN] [08-09|09:24:53.848] [NewPayload] Previously known bad block  hash=0x6ec18e10b257326452b249705b66350c3ef2963da75da9e769c065ca0401938a
[WARN] [08-09|09:24:56.661] [NewPayload] Previously known bad block  hash=0x6ec18e10b257326452b249705b66350c3ef2963da75da9e769c065ca0401938a
[WARN] [08-09|09:24:59.044] [NewPayload] Previously known bad block  hash=0x6ec18e10b257326452b249705b66350c3ef2963da75da9e769c065ca0401938a
[WARN] [08-09|09:25:01.705] [NewPayload] Previously known bad block  hash=0x6ec18e10b257326452b249705b66350c3ef2963da75da9e769c065ca0401938a
[WARN] [08-09|09:25:04.855] [NewPayload] Previously known bad block  hash=0x6ec18e10b257326452b249705b66350c3ef2963da75da9e769c065ca0401938a
[INFO] [08-09|09:25:07.862] [txpool] stat                            block=1658817 pending=224 baseFee=0 queued=183 alloc=62.0MB sys=132.3MB
[WARN] [08-09|09:25:07.888] [NewPayload] Previously known bad block  hash=0x6ec18e10b257326452b249705b66350c3ef2963da75da9e769c065ca0401938a
```

**Comment by nisdas** [comment]
@artjoma 
```
[WARN] [08-09|09:24:09.437] [5/7 Execution] Execution failed         block=1658817 hash=0x6ec18e10b257326452b249705b66350c3ef2963da75da9e769c065ca0401938a err="could not apply tx 0 from block 1658817 [0xa7261682ce6b1f5d70bdacb4ee13dbf466f72e9149cfc1a756031654c180f268]: nonce too low: address 0x2f14582947E292a2eCd20C430B46f2d27CFE213c, tx: 0 state: 7"
[WARN] [08-09|09:24:09.437] Could not validate block                 err="[5/7 Execution] could not apply tx 0 from block 1658817 [0xa7261682ce6b1f5d70bdacb4ee13dbf466f72e9149cfc1a756031654c180f268]: nonce too low: address 0x2f14582947E292a2eCd20C430B46f2d27CFE213c, tx: 0 state: 7"
[WARN] [08-09|09:24:09.437] Validation failed for header             hash=0x6ec18e10b257326452b249705b66350c3ef2963da75da9e769c065ca0401938a height=1658817 err="[5/7 Execution] could not apply tx 0 from block 1658817 [0xa7261682ce6b1f5d70bdacb4ee13dbf466f72e9149cfc1a756031654c180f268]: nonce too low: address 0x2f14582947E292a2eCd20C430B46f2d27CFE213c, tx: 0 state: 7"
```
This might be the reason it is failing, it appears to be a bug in erigon then.

**Comment by nisdas** [comment]
```
[WARN] [08-09|09:24:12.270] [NewPayload] Previously known bad block  hash=0x6ec18e10b257326452b249705b66350c3ef2963da75da9e769c065ca0401938a
[WARN] [08-09|09:24:15.637] [NewPayload] Previously known bad block  hash=0x6ec18e10b257326452b249705b66350c3ef2963da75da9e769c065ca0401938a
[WARN] [08-09|09:24:18.482] [NewPayload] Previously known bad block  hash=0x6ec18e10b257326452b249705b66350c3ef2963da75da9e769c065ca0401938a
[WARN] [08-09|09:24:21.679] [NewPayload] Previously known bad block  hash=0x6ec18e10b257326452b249705b66350c3ef2963da75da9e769c065ca0401938a
[WARN] [08-09|09:24:24.255] [NewPayload] Previously known bad block  hash=0x6ec18e10b257326452b249705b66350c3ef2963da75da9e769c065ca0401938a
[WARN] [08-09|09:24:28.092] [NewPayload] Previously known bad block  hash=0x6ec18e10b257326452b249705b66350c3ef2963da75da9e769c065ca0401938a
[WARN] [08-09|09:24:30.624] [NewPayload] Previously known bad block  hash=0x6ec18e10b257326452b249705b66350c3ef2963da75da9e769c065ca0401938a
[WARN] [08-09|09:24:33.085] [NewPayload] Previously known bad block  hash=0x6ec18e10b257326452b249705b66350c3ef2963da75da9e769c065ca0401938a
[WARN] [08-09|09:24:36.467] [NewPayload] Previously known bad block  hash=0x6ec18e10b257326452b249705b66350c3ef2963da75da9e769c065ca0401938a
```
It keeps on rejecting the payloads from the beacon node.

**Comment by nisdas** [comment]
This is a valid block that erigon keeps on rejecting:
https://sepolia.etherscan.io/block/0x6ec18e10b257326452b249705b66350c3ef2963da75da9e769c065ca0401938a

**Comment by artjoma** [comment]
@nisdas thank you! Created Erigon new issue: https://github.com/ledgerwatch/erigon/issues/4977

**Comment by artjoma** [comment]
Solved. Look at: https://github.com/ledgerwatch/erigon/issues/4977

**Comment by nisdas** [comment]
Not exactly, you linked a different error from above. Will link this to the issue.

**Comment by terencechain** [comment]
Please reopen if this issue still persists
