### ISSUE TITLE
Goerli sync failed

### ISSUE THREAD

**Issue by cgitmast** [prysmaticlabs/prysm#13478]
### Describe the bug

Sync stop on ETH block 10388237

Prysm log:
```
==> prysm-service.log <==
 time="2024-01-17 10:04:22" level=error msg="Could not process slots to get payload attribute" error="could not process slots: could not process epoch: could not process registry updates: could not get active validator count: could not interface with committee cache: context deadline exceeded" prefix=blockchain
 time="2024-01-17 10:04:28" level=warning msg="Execution client is not syncing" prefix=powchain
```
Geth v1.13.10
Prysm version v4.2.0

**Comment by nisdas** [comment]
@cgitmast This is fixed here:
https://github.com/prysmaticlabs/prysm/pull/13477

**Comment by cgitmast** [comment]
> @cgitmast This is fixed here: #13477

@nisdas I'm sorry but I don't understand what should I do...

**Comment by cgitmast** [comment]
I got new logs
```
==> prysm-service.log <==
 time="2024-01-17 10:17:54" level=warning msg="Block processing failure" error="failed to validate consensus state transition function: could not execute state transition: could not validate state root, wanted: 0x0498b3bee228592e79df7c54fa568adbfc463919bf02c35d7990dfe01f71e392, received: 0xcaedd8c6d9dc0162b57b0ddf63f75c43a38c4bdb137516df2288799ff604bade" firstSlot=7413758 firstUnprocessed=7413760 lastSlot=7413760 prefix=initial-sync root=0x92d898cb189bae13cb97db2818ec1426dc1ce9047f1d184790eca8d0a4995135
 time="2024-01-17 10:18:00" level=warning msg="Execution client is not syncing" prefix=powchain
 time="2024-01-17 10:18:07" level=info msg="Peer summary" activePeers=59 inbound=34 outbound=25 prefix=p2p
 time="2024-01-17 10:18:14" level=warning msg="Execution client is not syncing" prefix=powchain
 time="2024-01-17 10:18:28" level=warning msg="Execution client is not syncing" prefix=powchain
 time="2024-01-17 10:18:30" level=info msg="Processing block 0x92d898cb... 7413760/7414892 - estimated time remaining 6h17m20s" blocksPerSecond=0.1 peers=61 prefix=initial-sync
```

**Comment by cgitmast** [comment]
@nisdas Thank you!

**Comment by Jony321** [comment]
@nisdas 
I tried to use the image you suggested, but the problem remains, the node does not synchronize, and prism shuts down with an error.

Version from logs
`time="2024-01-17 20:05:37" level=info msg="Starting beacon node" prefix=node version="Prysm/v4.1.1/fe431b9201272220e83565634e5527d33b568c96. Built at: 2024-01-17 08:21:34+00:00"`

<details close>
<summary>Last lines before the big trace output</summary>
<br>

```
time="2024-01-17 20:17:21" level=info msg="Processing block batch of size 42 starting from  0x60ab3457... 7413727/7417886 - estimated time remai
ning 33m0s" blocksPerSecond=2.1 peers=22 prefix=initial-sync
time="2024-01-17 20:17:23" level=warning msg="Execution client is not syncing" prefix=execution
time="2024-01-17 20:17:37" level=warning msg="Execution client is not syncing" prefix=execution
time="2024-01-17 20:17:41" level=info msg="Called new payload with optimistic block" payloadBlockHash=0x8db647a21226 prefix=blockchain slot=7413
762
time="2024-01-17 20:17:41" level=info msg="Called new payload with optimistic block" payloadBlockHash=0xfebe087b7de5 prefix=blockchain slot=7413
763
time="2024-01-17 20:17:41" level=info msg="Called new payload with optimistic block" payloadBlockHash=0x9ccb3ba48b23 prefix=blockchain slot=7413
766
time="2024-01-17 20:17:41" level=info msg="Called new payload with optimistic block" payloadBlockHash=0x9e1658245657 prefix=blockchain slot=7413769
SIGILL: illegal instruction
PC=0x2158ddc m=4 sigcode=2
instruction bytes: 0xc5 0x7a 0x6f 0x2d 0x7c 0xee 0xbb 0xfe 0xc5 0x7a 0x6f 0x15 0xf4 0xa2 0xb9 0xfe
goroutine 34115 [running]:
github.com/prysmaticlabs/gohashtree._hash(0xc0b8394740, {0xc0b8394740, 0x2, 0x2}, 0x1)
        external/com_github_prysmaticlabs_gohashtree/hash_amd64.s:1061 +0x79dc fp=0xc0461fd568 sp=0xc0461fd1b8 pc=0x2158ddc
created by github.com/prysmaticlabs/prysm/v4/runtime.(*ServiceRegistry).StartAll in goroutine 1
        runtime/service_registry.go:46 +0xe7
goroutine 1 [chan receive, 4 minutes]:
runtime.gopark(...)
        GOROOT/src/runtime/proc.go:398
runtime.chanrecv(0xc000582000, 0x0, 0x1)
```
</details>

<details close>
<summary>Launch arguments</summary>
<br>

```
            "--datadir=/data/ethereum",
            "--jwt-secret=/data/ethereum/jwt.hex",
            "--rpc-host=0.0.0.0",
            "--grpc-gateway-host=0.0.0.0",
            "--monitoring-host=0.0.0.0",
            "--execution-endpoint=/data/ethereum/geth.ipc",
            "--accept-terms-of-use",
            "--goerli",
            "--checkpoint-sync-url=https://goerli.checkpoint-sync.ethpandaops.io",
            "--genesis-beacon-api-url=https://goerli.checkpoint-sync.ethpandaops.io",
            "--genesis-state=/data/ethereum/genesis.ssz"
```

</details>

Am I doing something wrong?

**Comment by nisdas** [comment]
This looks like a different issue entirely @Jony321 , does prysm work on your machine ? The error you get is a `SIGILL` here.

**Comment by potuz** [comment]
@Jony321 could you open a new issue with a full description of the CPU you're using and of there's emulators in place?

**Comment by cgitmast** [comment]
This issue is solved

**Comment by Jony321** [comment]
@nisdas 
It works for about 10 minutes after startup and turns off with an error.
Looks like another bug, I agree.

@potuz 
Yes, of course, I will open it soon.
Thank you!
