### ISSUE TITLE
Slasher Could not insert attester slashing into pool

### ISSUE THREAD

**Issue by Phistr90** [prysmaticlabs/prysm#5571]
# 🐞 Bug Report

### Description

Running the slasher I am getting this error from time to time and I am unable to slash anyone:

`[2020-04-21 22:48:11]  INFO detection: Found an attester slashing! Submitting to beacon node indices=[11957] sourceEpoch=869 surroundVote=false targetEpoch=870
[2020-04-21 22:48:11] ERROR beaconclient: rpc error: code = Internal desc = Could not insert attester slashing into pool: could not verify attester slashing: could not validate indexed attestation: signature did not verify`
 

### Has this worked before in a previous version?

This issue didnt occur the day after the genesis.

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Linux Ubuntu 18.04
  </code>
</pre>

**What version of Prysm are you running? (Which release)**

<pre>
  <code>
639e3072fe5f7cc335ad25d8b4a6cb386ad03a41
  </code>
</pre>

**Comment by nisdas** [comment]
@shayzluf @0xKiwi , from what I understand this is an ongoing problem correct with the slasher, correct ?

**Comment by 0xKiwi** [comment]
Yes, I think it might be related to #5306 based off of what we've seen.

**Comment by Phistr90** [comment]
finally slashed myself and not getting above error so far.
I am running the slasher now on 95f1676d5f9b66d079f67a6206ca075dd633165a
I guess that between that and commit 639e3072fe5f7cc335ad25d8b4a6cb386ad03a41 a bug has been introduced.

**Comment by rauljordan** [comment]
Resolved by the stream duties functionality in #5849

**Comment by 0xKiwi** [comment]
Reopening as this issue is not confirmed to be solved, once it is confirmed if #5849 solves this, we can close it.

**Comment by handelaar2** [comment]
Ran a slasher on the schlesi network with commit aed9e0e . Beacon and validator have same commit. There were many attester slashing events last Saturday. The slasher detected them successfully, but failed to add them to the pool due to the error:
 `ERROR beaconclient: rpc error: code = Internal desc = Could not insert attester slashing into pool: could not verify attester slashing: could not validate indexed attestation: signature did not verify`

This issue has been reopened since my slasher already ran the intended fix (#5849)
![2020-05-18_19-59-15](https://user-images.githubusercontent.com/28559038/82246692-74d30100-9945-11ea-9508-da595673b4b0.png)

So it looks to me that the issue is still there. Here is part of the relevant slasher log:
![2020-05-18_20-24-48](https://user-images.githubusercontent.com/28559038/82246877-c8454f00-9945-11ea-8d8e-d8cfe33ef942.png)

Slasher start command:
`/home/ubuntu/prysm/bazel-bin/slasher/linux_amd64_stripped/slasher \
--verbosity=info`

Beacon start command:
`/home/ubuntu/prysm/bazel-bin/beacon-chain/linux_amd64_stripped/beacon-chain \
--datadir="/home/ubuntu/.eth2" \
--verbosity=info \
--schlesi-testnet \
--grpc-gateway-port=4001 \
--dev \
--enable-new-state-mgmt  \
--disable-dynamic-committee-subnets \
--p2p-host-ip=$(curl -s v4.ident.me) \
--min-sync-peers 2 \
--p2p-max-peers=30 \
--contract-deployment-block 2596126 \
--deposit-contract "0xA15554BF93a052669B511ae29EA21f3581677ac5" \
--custom-genesis-delay 3600 \
--bootstrap-node "enr:-LK4QJ-6k6QytxOn7P9BdDZHXesHz3aaglpvo-VcTGc-rfr5H4DBzjQsjg6stZoy1H-p3yK21IISkJHe742QTVwRS_IEh2F0dG5ldHOIAAAAAAAAAACEZXRoMpCZJe_WAAAAAP__________gmlkgnY0gmlwhDMPd52Jc2VjcDI1NmsxoQINdLr6UY7y2CzshX4n_BbdYM1G40rpdEs84Mdoyv_ZyYN0Y3CCIyiDdWRwgiMo" \
--bootstrap-node "enr:-LK4QJS5Rn_kkA2MQpieVDUao5vkBj3kE15S_JJepGA9MNfndwHyfBWSjmAa5T_qvkGklrDiZXqlIAahXTm_eH_IXY8Ch2F0dG5ldHOIAAAAAAAAAACEZXRoMpCZJe_WAAAAAP__________gmlkgnY0gmlwhDMPd52Jc2VjcDI1NmsxoQOS1-hRSwsxLo2PH3RKtwWdjLdT1IMX2nqkQAlHs5E7LIN0Y3CCMsiDdWRwgi7g" \
--peer="/ip4/51.15.119.157/tcp/9000/p2p/16Uiu2HAkvLCWwVEfF365ZWXB6siDL1mUpcd1XQ1nSXAHmvM5W7wn" \
--peer="/ip4/51.15.119.157/tcp/9500/p2p/16Uiu2HAmSUvW1q4yH4QzZGpWHrLvpCzPdufSFex5odbhNj6zDEjQ" \
--peer="/ip4/51.15.119.157/tcp/13000/p2p/16Uiu2HAmNYCpko7ahZrZrzcpJRjL6bJ3JmPFiCbb9bgR3UHbHBsH" \
--peer="/ip4/51.15.119.157/tcp/13000/p2p/16Uiu2HAmJFyHbf5k6sC26Hmgniqo9cUaSgtM46tdzfFCA2wkqpoT" \
--peer="/ip4/51.15.119.157/tcp/13500/p2p/16Uiu2HAm37N426LzqRQF7YCo2u7HRCkAGrxPhv4QHxGu6YE51YWJ"`

Fore completeness, --dev parameters (active on beacon) are: 
![2020-05-18_20-29-48](https://user-images.githubusercontent.com/28559038/82247232-5a4d5780-9946-11ea-8a67-e27f102ac305.png)

**Comment by prestonvanloon** [comment]
Why would #5849 solve this? @0xKiwi

**Comment by 0xKiwi** [comment]
> Why would #5849 solve this? @0xKiwi 

We still don't know the root cause of the issue, it might occur when there is a reorg over an epoch boundary and the validator clients think they still belong to the previous committee (from before the reorg) and as a result the attestations they sign don't match the actual committees in the state. 
Streaming duties could solve this by not having validators act with out-of-date roles. Does that explain?

**Comment by prestonvanloon** [comment]
No, it doesn't quite explain it. How does validator assignments / duties have anything to do with the ability to insert an attester slashing into the attester slashing pool?

**Comment by rauljordan** [comment]
Latest status on this @0xKiwi ?

**Comment by 0xKiwi** [comment]
Haven't seen this in a while but nothing has really changed, I feel they arise during times of instability which would point to different committee calculation or something. Still not sure at all.

**Comment by rauljordan** [comment]
We will close this for now unless observed once again

**Comment by alexfisher** [comment]
FWIW, I'm seeing this error tonight for the first time repeatedly (after updating from the Medalla time problem today).

I'm seeing many iterations of the error at the same time stamp.  I have logs going to Papertrail and it reports something like at least 4000 copies of this error over the last couple hours.
