### ISSUE TITLE
peers without a static ip and port forwarding

### ISSUE THREAD

**Issue by ChuckNorrison** [prysmaticlabs/prysm#7373]
lighthouse can read public ip from udp packets and make use of it

no chance for the prysm to get used without a static public ip or dyndns?

**Comment by ChuckNorrison** [comment]
peers should be found prior genesis to get some work done which was not expected...

**Comment by nisdas** [comment]
@ChuckNorrison This has been fixed in `master` , the bootstrap- node isnt baked into alpha.26. So the node will not be able to find any peers. If you can come on discord, we can get the node setup for you.

**Comment by ChuckNorrison** [comment]
Thanks for your response. This will fail for some reasons, prysm does not work for me. 

I need:
- port forwardings
- IPv4 support, even IPv6 is active 
- Public IP parsed from UDP packets automatically to find peers

All this will make me force to use another client

**Comment by nisdas** [comment]
@ChuckNorrison you dont need a static ip or need to portforward. Prysm is able to determine its IP from inbound packets. All you do need is a bootstrap-node. so please try with this flag 
```
--bootstrap-node=enr:-Ku4QGQJf2bcDAwVGvbvtq3AB4KKwAvStTenY-i_QnW2ABNRRBncIU_5qR_e_um-9t3s9g-Y5ZfFATj1nhtzq6lvgc4Bh2F0dG5ldHOIAAAAAAAAAACEZXRoMpDEqCQNAAAAAv__gmlkgnY0gmlwhBLf22SJc2VjcDI1NmsxoQNoed9JnQh7ltcAacHEGOjwocL1BhMQbYTgaPX0kFuXtIN1ZHCCE4g
--clear-db
```
Please re-run the node with these flags. This should fix your issues

**Comment by ChuckNorrison** [comment]
`level=error msg="Invalid address of enr:-Ku4QGQJf2bcDAwVGvbvtq3AB4KKwAvStTenY-i_QnW2ABNRRBncIU_5qR_e_um-9t3s9g-Y5ZfFATj1nhtzq6lvgc4Bh2F0dG5ldHOIAAAAAAAAAACEZXRoMpDEqCQNAAAAAv__gmlkgnY0gmlwhBLf22SJc2VjcDI1NmsxoQNoed9JnQh7ltcAacHEGOjwocL1BhMQbYTgaPX0kFuXtIN1ZHCCE4g provided: failed to parse multiaddr "enr:-Ku4QGQJf2bcDAwVGvbvtq3AB4KKwAvStTenY-i_QnW2ABNRRBncIU_5qR_e_um-9t3s9g-Y5ZfFATj1nhtzq6lvgc4Bh2F0dG5ldHOIAAAAAAAAAACEZXRoMpDEqCQNAAAAAv__gmlkgnY0gmlwhBLf22SJc2VjcDI1NmsxoQNoed9JnQh7ltcAacHEGOjwocL1BhMQbYTgaPX0kFuXtIN1ZHCCE4g": must begin with /" prefix=p2p`

**Comment by nisdas** [comment]
sorry @ChuckNorrison , try this one. 
```
--bootstrap-node=enr:-Ku4QGQJf2bcDAwVGvbvtq3AB4KKwAvStTenY-i_QnW2ABNRRBncIU_5qR_e_um-9t3s9g-Y5ZfFATj1nhtzq6lvgc4Bh2F0dG5ldHOIAAAAAAAAAACEZXRoMpDEqCQNAAAAAv__________gmlkgnY0gmlwhBLf22SJc2VjcDI1NmsxoQNoed9JnQh7ltcAacHEGOjwocL1BhMQbYTgaPX0kFuXtIN1ZHCCE4g --clear-db
```

**Comment by ChuckNorrison** [comment]
Ok this is working with the bootnode, sorry i was a bit mad this does not flow as i hoped and i missed a possibility to make sure everything works fine prior spadina genesis. 

Further it seems the validator and slahser instances needs to always restart with the beacon instance. They will not reconnect my beacon if it got restarted. Maybe this gets solved with .27?

Thanks for your support

**Comment by nisdas** [comment]
@ChuckNorrison Understood , this was a bad on our part. We have this all fixed in the latest master, however this was not released in the current latest release (alpha.26). This is the primary reason for the current difficulties. We will be releasing alpha.27 today with all the fixes, so it should make your life a lot easier.

**Comment by ChuckNorrison** [comment]
even after .27 it needs another --force-clear-db and resync and another bunch of missing attestations got thrown cause it needs another 10 min to to recognize that some output is missing... After RPC connection success this instance hangs even in version .27

**Comment by nisdas** [comment]
Hey @ChuckNorrison definitely understood, the issue has been patched in master so a new user will not have to `force-clear-db` anymore. This shouldnt be an issue as of the current moment as it only happens in certain edge cases right after genesis. Those edge cases have been resolved for now and the fix will be included in alpha.28 .

**Comment by ChuckNorrison** [comment]
this is still an issue with current beta.0. No peers since yesterday. After update it seems to works for some time. After restart the service today it can not find any peers.

**Comment by nisdas** [comment]
Hey @ChuckNorrison given that spadina and zinken are intended to be short-term testnets, peer discovery in our beta release is not backwards compatible with most spadina nodes. In beta, we updated our discovery to v5.1 which is a breaking change, which is why you see 0 peers. You can use our alpha versions to be able to run on spadina.

**Comment by ChuckNorrison** [comment]
Thanks, i was not aware of that fact. We still have some testnet flags available which do not work anymore
